//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Film.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filmler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filmler()
        {
            this.Incelemelers = new HashSet<Incelemeler>();
            this.Kullanici_Favorileri = new HashSet<Kullanici_Favorileri>();
        }
    
        public int film_id { get; set; }
        public string baslik { get; set; }
        public string yonetmen { get; set; }
        public string kategori { get; set; }
        public string yayin_tarihi { get; set; }
        public string aciklama { get; set; }
        public Nullable<decimal> ortalama_puan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incelemeler> Incelemelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici_Favorileri> Kullanici_Favorileri { get; set; }
    }
}
