//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Film.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class yettiEntities2 : DbContext
    {
        public yettiEntities2()
            : base("name=yettiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Filmler> Filmlers { get; set; }
        public virtual DbSet<Incelemeler> Incelemelers { get; set; }
        public virtual DbSet<Kullanici_Favorileri> Kullanici_Favorileri { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
    }
}
