//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM İlişkisi Meta Verileri

[assembly: EdmRelationshipAttribute("yettiModel", "FK__Incelemel__film___3C69FB99", "Filmler", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Film.Models.Filmler), "Incelemeler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Film.Models.Incelemeler), true)]
[assembly: EdmRelationshipAttribute("yettiModel", "FK__Kullanici__film___403A8C7D", "Filmler", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Film.Models.Filmler), "Kullanici_Favorileri", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Film.Models.Kullanici_Favorileri), true)]
[assembly: EdmRelationshipAttribute("yettiModel", "FK__Incelemel__kulla__3B75D760", "Kullanicilar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Film.Models.Kullanicilar), "Incelemeler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Film.Models.Incelemeler), true)]
[assembly: EdmRelationshipAttribute("yettiModel", "FK__Kullanici__kulla__3F466844", "Kullanicilar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Film.Models.Kullanicilar), "Kullanici_Favorileri", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Film.Models.Kullanici_Favorileri), true)]

#endregion

namespace Film.Models
{
    #region Bağlamlar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    public partial class yettiEntities : ObjectContext
    {
        #region Oluşturucular
    
        /// <summary>
        /// Yeni yettiEntities nesnesini, uygulama yapılandırma dosyasının 'yettiEntities' bölümünde bulunan bağlantı dizesini kullanarak başlatır.
        /// </summary>
        public yettiEntities() : base("name=yettiEntities", "yettiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir yettiEntities nesnesi başlatın.
        /// </summary>
        public yettiEntities(string connectionString) : base(connectionString, "yettiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir yettiEntities nesnesi başlatın.
        /// </summary>
        public yettiEntities(EntityConnection connection) : base(connection, "yettiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Kısmi Metotlar
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<Filmler> Filmlers
        {
            get
            {
                if ((_Filmlers == null))
                {
                    _Filmlers = base.CreateObjectSet<Filmler>("Filmlers");
                }
                return _Filmlers;
            }
        }
        private ObjectSet<Filmler> _Filmlers;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<Incelemeler> Incelemelers
        {
            get
            {
                if ((_Incelemelers == null))
                {
                    _Incelemelers = base.CreateObjectSet<Incelemeler>("Incelemelers");
                }
                return _Incelemelers;
            }
        }
        private ObjectSet<Incelemeler> _Incelemelers;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<Kullanici_Favorileri> Kullanici_Favorileri
        {
            get
            {
                if ((_Kullanici_Favorileri == null))
                {
                    _Kullanici_Favorileri = base.CreateObjectSet<Kullanici_Favorileri>("Kullanici_Favorileri");
                }
                return _Kullanici_Favorileri;
            }
        }
        private ObjectSet<Kullanici_Favorileri> _Kullanici_Favorileri;
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        public ObjectSet<Kullanicilar> Kullanicilars
        {
            get
            {
                if ((_Kullanicilars == null))
                {
                    _Kullanicilars = base.CreateObjectSet<Kullanicilar>("Kullanicilars");
                }
                return _Kullanicilars;
            }
        }
        private ObjectSet<Kullanicilar> _Kullanicilars;

        #endregion

        #region AddTo Metotları
    
        /// <summary>
        /// Filmlers EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToFilmlers(Filmler filmler)
        {
            base.AddObject("Filmlers", filmler);
        }
    
        /// <summary>
        /// Incelemelers EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToIncelemelers(Incelemeler incelemeler)
        {
            base.AddObject("Incelemelers", incelemeler);
        }
    
        /// <summary>
        /// Kullanici_Favorileri EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToKullanici_Favorileri(Kullanici_Favorileri kullanici_Favorileri)
        {
            base.AddObject("Kullanici_Favorileri", kullanici_Favorileri);
        }
    
        /// <summary>
        /// Kullanicilars EntitySet'e yeni nesne ekleme için Deprecated Metodu. Bunun yerine, ilişkili ObjectSet&lt;T&gt; özelliğinin .Add metodunu kullanmayı deneyin.
        /// </summary>
        public void AddToKullanicilars(Kullanicilar kullanicilar)
        {
            base.AddObject("Kullanicilars", kullanicilar);
        }

        #endregion

    }

    #endregion

    #region Varlıklar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yettiModel", Name="Filmler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Filmler : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir Filmler nesnesi oluşturun.
        /// </summary>
        /// <param name="film_id">film_id özelliğinin ilk değeri.</param>
        public static Filmler CreateFilmler(global::System.Int32 film_id)
        {
            Filmler filmler = new Filmler();
            filmler.film_id = film_id;
            return filmler;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 film_id
        {
            get
            {
                return _film_id;
            }
            set
            {
                if (_film_id != value)
                {
                    Onfilm_idChanging(value);
                    ReportPropertyChanging("film_id");
                    _film_id = StructuralObject.SetValidValue(value, "film_id");
                    ReportPropertyChanged("film_id");
                    Onfilm_idChanged();
                }
            }
        }
        private global::System.Int32 _film_id;
        partial void Onfilm_idChanging(global::System.Int32 value);
        partial void Onfilm_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String baslik
        {
            get
            {
                return _baslik;
            }
            set
            {
                OnbaslikChanging(value);
                ReportPropertyChanging("baslik");
                _baslik = StructuralObject.SetValidValue(value, true, "baslik");
                ReportPropertyChanged("baslik");
                OnbaslikChanged();
            }
        }
        private global::System.String _baslik;
        partial void OnbaslikChanging(global::System.String value);
        partial void OnbaslikChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String yonetmen
        {
            get
            {
                return _yonetmen;
            }
            set
            {
                OnyonetmenChanging(value);
                ReportPropertyChanging("yonetmen");
                _yonetmen = StructuralObject.SetValidValue(value, true, "yonetmen");
                ReportPropertyChanged("yonetmen");
                OnyonetmenChanged();
            }
        }
        private global::System.String _yonetmen;
        partial void OnyonetmenChanging(global::System.String value);
        partial void OnyonetmenChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kategori
        {
            get
            {
                return _kategori;
            }
            set
            {
                OnkategoriChanging(value);
                ReportPropertyChanging("kategori");
                _kategori = StructuralObject.SetValidValue(value, true, "kategori");
                ReportPropertyChanged("kategori");
                OnkategoriChanged();
            }
        }
        private global::System.String _kategori;
        partial void OnkategoriChanging(global::System.String value);
        partial void OnkategoriChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String yayin_tarihi
        {
            get
            {
                return _yayin_tarihi;
            }
            set
            {
                Onyayin_tarihiChanging(value);
                ReportPropertyChanging("yayin_tarihi");
                _yayin_tarihi = StructuralObject.SetValidValue(value, true, "yayin_tarihi");
                ReportPropertyChanged("yayin_tarihi");
                Onyayin_tarihiChanged();
            }
        }
        private global::System.String _yayin_tarihi;
        partial void Onyayin_tarihiChanging(global::System.String value);
        partial void Onyayin_tarihiChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aciklama
        {
            get
            {
                return _aciklama;
            }
            set
            {
                OnaciklamaChanging(value);
                ReportPropertyChanging("aciklama");
                _aciklama = StructuralObject.SetValidValue(value, true, "aciklama");
                ReportPropertyChanged("aciklama");
                OnaciklamaChanged();
            }
        }
        private global::System.String _aciklama;
        partial void OnaciklamaChanging(global::System.String value);
        partial void OnaciklamaChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ortalama_puan
        {
            get
            {
                return _ortalama_puan;
            }
            set
            {
                Onortalama_puanChanging(value);
                ReportPropertyChanging("ortalama_puan");
                _ortalama_puan = StructuralObject.SetValidValue(value, "ortalama_puan");
                ReportPropertyChanged("ortalama_puan");
                Onortalama_puanChanged();
            }
        }
        private Nullable<global::System.Decimal> _ortalama_puan;
        partial void Onortalama_puanChanging(Nullable<global::System.Decimal> value);
        partial void Onortalama_puanChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("yettiModel", "FK__Incelemel__film___3C69FB99", "Incelemeler")]
        public EntityCollection<Incelemeler> Incelemelers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Incelemeler>("yettiModel.FK__Incelemel__film___3C69FB99", "Incelemeler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Incelemeler>("yettiModel.FK__Incelemel__film___3C69FB99", "Incelemeler", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("yettiModel", "FK__Kullanici__film___403A8C7D", "Kullanici_Favorileri")]
        public EntityCollection<Kullanici_Favorileri> Kullanici_Favorileri
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kullanici_Favorileri>("yettiModel.FK__Kullanici__film___403A8C7D", "Kullanici_Favorileri");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kullanici_Favorileri>("yettiModel.FK__Kullanici__film___403A8C7D", "Kullanici_Favorileri", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yettiModel", Name="Incelemeler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Incelemeler : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir Incelemeler nesnesi oluşturun.
        /// </summary>
        /// <param name="inceleme_id">inceleme_id özelliğinin ilk değeri.</param>
        public static Incelemeler CreateIncelemeler(global::System.Int32 inceleme_id)
        {
            Incelemeler incelemeler = new Incelemeler();
            incelemeler.inceleme_id = inceleme_id;
            return incelemeler;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 inceleme_id
        {
            get
            {
                return _inceleme_id;
            }
            set
            {
                if (_inceleme_id != value)
                {
                    Oninceleme_idChanging(value);
                    ReportPropertyChanging("inceleme_id");
                    _inceleme_id = StructuralObject.SetValidValue(value, "inceleme_id");
                    ReportPropertyChanged("inceleme_id");
                    Oninceleme_idChanged();
                }
            }
        }
        private global::System.Int32 _inceleme_id;
        partial void Oninceleme_idChanging(global::System.Int32 value);
        partial void Oninceleme_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> kullanici_id
        {
            get
            {
                return _kullanici_id;
            }
            set
            {
                Onkullanici_idChanging(value);
                ReportPropertyChanging("kullanici_id");
                _kullanici_id = StructuralObject.SetValidValue(value, "kullanici_id");
                ReportPropertyChanged("kullanici_id");
                Onkullanici_idChanged();
            }
        }
        private Nullable<global::System.Int32> _kullanici_id;
        partial void Onkullanici_idChanging(Nullable<global::System.Int32> value);
        partial void Onkullanici_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> film_id
        {
            get
            {
                return _film_id;
            }
            set
            {
                Onfilm_idChanging(value);
                ReportPropertyChanging("film_id");
                _film_id = StructuralObject.SetValidValue(value, "film_id");
                ReportPropertyChanged("film_id");
                Onfilm_idChanged();
            }
        }
        private Nullable<global::System.Int32> _film_id;
        partial void Onfilm_idChanging(Nullable<global::System.Int32> value);
        partial void Onfilm_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String inceleme_metni
        {
            get
            {
                return _inceleme_metni;
            }
            set
            {
                Oninceleme_metniChanging(value);
                ReportPropertyChanging("inceleme_metni");
                _inceleme_metni = StructuralObject.SetValidValue(value, true, "inceleme_metni");
                ReportPropertyChanged("inceleme_metni");
                Oninceleme_metniChanged();
            }
        }
        private global::System.String _inceleme_metni;
        partial void Oninceleme_metniChanging(global::System.String value);
        partial void Oninceleme_metniChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> yildiz_puani
        {
            get
            {
                return _yildiz_puani;
            }
            set
            {
                Onyildiz_puaniChanging(value);
                ReportPropertyChanging("yildiz_puani");
                _yildiz_puani = StructuralObject.SetValidValue(value, "yildiz_puani");
                ReportPropertyChanged("yildiz_puani");
                Onyildiz_puaniChanged();
            }
        }
        private Nullable<global::System.Int32> _yildiz_puani;
        partial void Onyildiz_puaniChanging(Nullable<global::System.Int32> value);
        partial void Onyildiz_puaniChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("yettiModel", "FK__Incelemel__film___3C69FB99", "Filmler")]
        public Filmler Filmler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filmler>("yettiModel.FK__Incelemel__film___3C69FB99", "Filmler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filmler>("yettiModel.FK__Incelemel__film___3C69FB99", "Filmler").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Filmler> FilmlerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filmler>("yettiModel.FK__Incelemel__film___3C69FB99", "Filmler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Filmler>("yettiModel.FK__Incelemel__film___3C69FB99", "Filmler", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("yettiModel", "FK__Incelemel__kulla__3B75D760", "Kullanicilar")]
        public Kullanicilar Kullanicilar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kullanicilar>("yettiModel.FK__Incelemel__kulla__3B75D760", "Kullanicilar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kullanicilar>("yettiModel.FK__Incelemel__kulla__3B75D760", "Kullanicilar").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kullanicilar> KullanicilarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kullanicilar>("yettiModel.FK__Incelemel__kulla__3B75D760", "Kullanicilar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kullanicilar>("yettiModel.FK__Incelemel__kulla__3B75D760", "Kullanicilar", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yettiModel", Name="Kullanici_Favorileri")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kullanici_Favorileri : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir Kullanici_Favorileri nesnesi oluşturun.
        /// </summary>
        /// <param name="favori_id">favori_id özelliğinin ilk değeri.</param>
        public static Kullanici_Favorileri CreateKullanici_Favorileri(global::System.Int32 favori_id)
        {
            Kullanici_Favorileri kullanici_Favorileri = new Kullanici_Favorileri();
            kullanici_Favorileri.favori_id = favori_id;
            return kullanici_Favorileri;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 favori_id
        {
            get
            {
                return _favori_id;
            }
            set
            {
                if (_favori_id != value)
                {
                    Onfavori_idChanging(value);
                    ReportPropertyChanging("favori_id");
                    _favori_id = StructuralObject.SetValidValue(value, "favori_id");
                    ReportPropertyChanged("favori_id");
                    Onfavori_idChanged();
                }
            }
        }
        private global::System.Int32 _favori_id;
        partial void Onfavori_idChanging(global::System.Int32 value);
        partial void Onfavori_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> kullanici_id
        {
            get
            {
                return _kullanici_id;
            }
            set
            {
                Onkullanici_idChanging(value);
                ReportPropertyChanging("kullanici_id");
                _kullanici_id = StructuralObject.SetValidValue(value, "kullanici_id");
                ReportPropertyChanged("kullanici_id");
                Onkullanici_idChanged();
            }
        }
        private Nullable<global::System.Int32> _kullanici_id;
        partial void Onkullanici_idChanging(Nullable<global::System.Int32> value);
        partial void Onkullanici_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> film_id
        {
            get
            {
                return _film_id;
            }
            set
            {
                Onfilm_idChanging(value);
                ReportPropertyChanging("film_id");
                _film_id = StructuralObject.SetValidValue(value, "film_id");
                ReportPropertyChanged("film_id");
                Onfilm_idChanged();
            }
        }
        private Nullable<global::System.Int32> _film_id;
        partial void Onfilm_idChanging(Nullable<global::System.Int32> value);
        partial void Onfilm_idChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("yettiModel", "FK__Kullanici__film___403A8C7D", "Filmler")]
        public Filmler Filmler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filmler>("yettiModel.FK__Kullanici__film___403A8C7D", "Filmler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filmler>("yettiModel.FK__Kullanici__film___403A8C7D", "Filmler").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Filmler> FilmlerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filmler>("yettiModel.FK__Kullanici__film___403A8C7D", "Filmler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Filmler>("yettiModel.FK__Kullanici__film___403A8C7D", "Filmler", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("yettiModel", "FK__Kullanici__kulla__3F466844", "Kullanicilar")]
        public Kullanicilar Kullanicilar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kullanicilar>("yettiModel.FK__Kullanici__kulla__3F466844", "Kullanicilar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kullanicilar>("yettiModel.FK__Kullanici__kulla__3F466844", "Kullanicilar").Value = value;
            }
        }
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kullanicilar> KullanicilarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kullanicilar>("yettiModel.FK__Kullanici__kulla__3F466844", "Kullanicilar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kullanicilar>("yettiModel.FK__Kullanici__kulla__3F466844", "Kullanicilar", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="yettiModel", Name="Kullanicilar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kullanicilar : EntityObject
    {
        #region Factory Metodu
    
        /// <summary>
        /// Yeni bir Kullanicilar nesnesi oluşturun.
        /// </summary>
        /// <param name="kullanici_id">kullanici_id özelliğinin ilk değeri.</param>
        public static Kullanicilar CreateKullanicilar(global::System.Int32 kullanici_id)
        {
            Kullanicilar kullanicilar = new Kullanicilar();
            kullanicilar.kullanici_id = kullanici_id;
            return kullanicilar;
        }

        #endregion

        #region Basit Özellikler
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 kullanici_id
        {
            get
            {
                return _kullanici_id;
            }
            set
            {
                if (_kullanici_id != value)
                {
                    Onkullanici_idChanging(value);
                    ReportPropertyChanging("kullanici_id");
                    _kullanici_id = StructuralObject.SetValidValue(value, "kullanici_id");
                    ReportPropertyChanged("kullanici_id");
                    Onkullanici_idChanged();
                }
            }
        }
        private global::System.Int32 _kullanici_id;
        partial void Onkullanici_idChanging(global::System.Int32 value);
        partial void Onkullanici_idChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ad
        {
            get
            {
                return _ad;
            }
            set
            {
                OnadChanging(value);
                ReportPropertyChanging("ad");
                _ad = StructuralObject.SetValidValue(value, true, "ad");
                ReportPropertyChanged("ad");
                OnadChanged();
            }
        }
        private global::System.String _ad;
        partial void OnadChanging(global::System.String value);
        partial void OnadChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String e_posta
        {
            get
            {
                return _e_posta;
            }
            set
            {
                One_postaChanging(value);
                ReportPropertyChanging("e_posta");
                _e_posta = StructuralObject.SetValidValue(value, true, "e_posta");
                ReportPropertyChanged("e_posta");
                One_postaChanged();
            }
        }
        private global::System.String _e_posta;
        partial void One_postaChanging(global::System.String value);
        partial void One_postaChanged();
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sifre_hash
        {
            get
            {
                return _sifre_hash;
            }
            set
            {
                Onsifre_hashChanging(value);
                ReportPropertyChanging("sifre_hash");
                _sifre_hash = StructuralObject.SetValidValue(value, true, "sifre_hash");
                ReportPropertyChanged("sifre_hash");
                Onsifre_hashChanged();
            }
        }
        private global::System.String _sifre_hash;
        partial void Onsifre_hashChanging(global::System.String value);
        partial void Onsifre_hashChanged();

        #endregion

        #region Gezinme Özellikleri
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("yettiModel", "FK__Incelemel__kulla__3B75D760", "Incelemeler")]
        public EntityCollection<Incelemeler> Incelemelers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Incelemeler>("yettiModel.FK__Incelemel__kulla__3B75D760", "Incelemeler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Incelemeler>("yettiModel.FK__Incelemel__kulla__3B75D760", "Incelemeler", value);
                }
            }
        }
    
        /// <summary>
        /// Kullanılabilir Meta Veri Belgeleri yok.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("yettiModel", "FK__Kullanici__kulla__3F466844", "Kullanici_Favorileri")]
        public EntityCollection<Kullanici_Favorileri> Kullanici_Favorileri
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Kullanici_Favorileri>("yettiModel.FK__Kullanici__kulla__3F466844", "Kullanici_Favorileri");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Kullanici_Favorileri>("yettiModel.FK__Kullanici__kulla__3F466844", "Kullanici_Favorileri", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
